// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: proto/battleship.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewGameRequest) Reset() {
	*x = NewGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battleship_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGameRequest) ProtoMessage() {}

func (x *NewGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battleship_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGameRequest.ProtoReflect.Descriptor instead.
func (*NewGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_battleship_proto_rawDescGZIP(), []int{0}
}

type NewGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID   string `protobuf:"bytes,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	PlayerID string `protobuf:"bytes,2,opt,name=playerID,proto3" json:"playerID,omitempty"`
}

func (x *NewGameResponse) Reset() {
	*x = NewGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battleship_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGameResponse) ProtoMessage() {}

func (x *NewGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battleship_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGameResponse.ProtoReflect.Descriptor instead.
func (*NewGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_battleship_proto_rawDescGZIP(), []int{1}
}

func (x *NewGameResponse) GetGameID() string {
	if x != nil {
		return x.GameID
	}
	return ""
}

func (x *NewGameResponse) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

type JoinGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID string `protobuf:"bytes,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
}

func (x *JoinGameRequest) Reset() {
	*x = JoinGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battleship_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameRequest) ProtoMessage() {}

func (x *JoinGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battleship_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameRequest.ProtoReflect.Descriptor instead.
func (*JoinGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_battleship_proto_rawDescGZIP(), []int{2}
}

func (x *JoinGameRequest) GetGameID() string {
	if x != nil {
		return x.GameID
	}
	return ""
}

type JoinGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerID string `protobuf:"bytes,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
}

func (x *JoinGameResponse) Reset() {
	*x = JoinGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battleship_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinGameResponse) ProtoMessage() {}

func (x *JoinGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battleship_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinGameResponse.ProtoReflect.Descriptor instead.
func (*JoinGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_battleship_proto_rawDescGZIP(), []int{3}
}

func (x *JoinGameResponse) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

type PlaceShipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID   string `protobuf:"bytes,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	PlayerID string `protobuf:"bytes,2,opt,name=playerID,proto3" json:"playerID,omitempty"`
	ShipName string `protobuf:"bytes,3,opt,name=shipName,proto3" json:"shipName,omitempty"`
	X        int32  `protobuf:"varint,4,opt,name=x,proto3" json:"x,omitempty"`
	Y        int32  `protobuf:"varint,5,opt,name=y,proto3" json:"y,omitempty"`
	Vertical bool   `protobuf:"varint,6,opt,name=vertical,proto3" json:"vertical,omitempty"`
}

func (x *PlaceShipRequest) Reset() {
	*x = PlaceShipRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battleship_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceShipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceShipRequest) ProtoMessage() {}

func (x *PlaceShipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battleship_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceShipRequest.ProtoReflect.Descriptor instead.
func (*PlaceShipRequest) Descriptor() ([]byte, []int) {
	return file_proto_battleship_proto_rawDescGZIP(), []int{4}
}

func (x *PlaceShipRequest) GetGameID() string {
	if x != nil {
		return x.GameID
	}
	return ""
}

func (x *PlaceShipRequest) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *PlaceShipRequest) GetShipName() string {
	if x != nil {
		return x.ShipName
	}
	return ""
}

func (x *PlaceShipRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlaceShipRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlaceShipRequest) GetVertical() bool {
	if x != nil {
		return x.Vertical
	}
	return false
}

type PlaceShipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PlaceShipResponse) Reset() {
	*x = PlaceShipResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battleship_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaceShipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceShipResponse) ProtoMessage() {}

func (x *PlaceShipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battleship_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceShipResponse.ProtoReflect.Descriptor instead.
func (*PlaceShipResponse) Descriptor() ([]byte, []int) {
	return file_proto_battleship_proto_rawDescGZIP(), []int{5}
}

type FireRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameID   string `protobuf:"bytes,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	PlayerID string `protobuf:"bytes,2,opt,name=playerID,proto3" json:"playerID,omitempty"`
	X        int32  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y        int32  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *FireRequest) Reset() {
	*x = FireRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battleship_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireRequest) ProtoMessage() {}

func (x *FireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battleship_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireRequest.ProtoReflect.Descriptor instead.
func (*FireRequest) Descriptor() ([]byte, []int) {
	return file_proto_battleship_proto_rawDescGZIP(), []int{6}
}

func (x *FireRequest) GetGameID() string {
	if x != nil {
		return x.GameID
	}
	return ""
}

func (x *FireRequest) GetPlayerID() string {
	if x != nil {
		return x.PlayerID
	}
	return ""
}

func (x *FireRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FireRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type FireResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *FireResponse) Reset() {
	*x = FireResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_battleship_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireResponse) ProtoMessage() {}

func (x *FireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battleship_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireResponse.ProtoReflect.Descriptor instead.
func (*FireResponse) Descriptor() ([]byte, []int) {
	return file_proto_battleship_proto_rawDescGZIP(), []int{7}
}

func (x *FireResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_proto_battleship_proto protoreflect.FileDescriptor

var file_proto_battleship_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x73, 0x68,
	0x69, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x73, 0x68, 0x69, 0x70, 0x22, 0x10, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x45, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x47, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x22, 0x29, 0x0a,
	0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x22, 0x2e, 0x0a, 0x10, 0x4a, 0x6f, 0x69, 0x6e,
	0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x22, 0x9a, 0x01, 0x0a, 0x10, 0x50, 0x6c, 0x61,
	0x63, 0x65, 0x53, 0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67,
	0x61, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x69, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x63, 0x61, 0x6c, 0x22, 0x13, 0x0a, 0x11, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x68,
	0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x5d, 0x0a, 0x0b, 0x46, 0x69,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x61, 0x6d,
	0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x44, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x44, 0x12, 0x0c, 0x0a,
	0x01, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x79, 0x22, 0x26, 0x0a, 0x0c, 0x46, 0x69, 0x72,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0xa4, 0x02, 0x0a, 0x0a, 0x42, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x73, 0x68, 0x69, 0x70,
	0x12, 0x44, 0x0a, 0x07, 0x4e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x2e, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x4e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65,
	0x73, 0x68, 0x69, 0x70, 0x2e, 0x4e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61,
	0x6d, 0x65, 0x12, 0x1b, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e,
	0x4a, 0x6f, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x4a, 0x6f, 0x69,
	0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4a, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x68, 0x69, 0x70, 0x12, 0x1c, 0x2e, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53,
	0x68, 0x69, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x62, 0x61, 0x74,
	0x74, 0x6c, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x53, 0x68, 0x69,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x04, 0x46,
	0x69, 0x72, 0x65, 0x12, 0x17, 0x2e, 0x62, 0x61, 0x74, 0x74, 0x6c, 0x65, 0x73, 0x68, 0x69, 0x70,
	0x2e, 0x46, 0x69, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x62,
	0x61, 0x74, 0x74, 0x6c, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2e, 0x46, 0x69, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x63, 0x6a, 0x75, 0x64, 0x64, 0x2f, 0x62, 0x61,
	0x74, 0x74, 0x6c, 0x65, 0x73, 0x68, 0x69, 0x70, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_battleship_proto_rawDescOnce sync.Once
	file_proto_battleship_proto_rawDescData = file_proto_battleship_proto_rawDesc
)

func file_proto_battleship_proto_rawDescGZIP() []byte {
	file_proto_battleship_proto_rawDescOnce.Do(func() {
		file_proto_battleship_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_battleship_proto_rawDescData)
	})
	return file_proto_battleship_proto_rawDescData
}

var file_proto_battleship_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_battleship_proto_goTypes = []interface{}{
	(*NewGameRequest)(nil),    // 0: battleship.NewGameRequest
	(*NewGameResponse)(nil),   // 1: battleship.NewGameResponse
	(*JoinGameRequest)(nil),   // 2: battleship.JoinGameRequest
	(*JoinGameResponse)(nil),  // 3: battleship.JoinGameResponse
	(*PlaceShipRequest)(nil),  // 4: battleship.PlaceShipRequest
	(*PlaceShipResponse)(nil), // 5: battleship.PlaceShipResponse
	(*FireRequest)(nil),       // 6: battleship.FireRequest
	(*FireResponse)(nil),      // 7: battleship.FireResponse
}
var file_proto_battleship_proto_depIdxs = []int32{
	0, // 0: battleship.Battleship.NewGame:input_type -> battleship.NewGameRequest
	2, // 1: battleship.Battleship.JoinGame:input_type -> battleship.JoinGameRequest
	4, // 2: battleship.Battleship.PlaceShip:input_type -> battleship.PlaceShipRequest
	6, // 3: battleship.Battleship.Fire:input_type -> battleship.FireRequest
	1, // 4: battleship.Battleship.NewGame:output_type -> battleship.NewGameResponse
	3, // 5: battleship.Battleship.JoinGame:output_type -> battleship.JoinGameResponse
	5, // 6: battleship.Battleship.PlaceShip:output_type -> battleship.PlaceShipResponse
	7, // 7: battleship.Battleship.Fire:output_type -> battleship.FireResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_battleship_proto_init() }
func file_proto_battleship_proto_init() {
	if File_proto_battleship_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_battleship_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_battleship_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_battleship_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_battleship_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_battleship_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceShipRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_battleship_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaceShipResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_battleship_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FireRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_battleship_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FireResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_battleship_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_battleship_proto_goTypes,
		DependencyIndexes: file_proto_battleship_proto_depIdxs,
		MessageInfos:      file_proto_battleship_proto_msgTypes,
	}.Build()
	File_proto_battleship_proto = out.File
	file_proto_battleship_proto_rawDesc = nil
	file_proto_battleship_proto_goTypes = nil
	file_proto_battleship_proto_depIdxs = nil
}
